"""Initial migration

Revision ID: 6aeb6423d3df
Revises:
Create Date: 2026-09-08 09:40:12.379397

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6aeb6423d3df"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country", sa.String(length=20), nullable=False),
        sa.Column("city", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "climb_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column(
            "discipline", sa.Enum("SPORT", "BOULDER", name="discipline"), nullable=False
        ),
        sa.Column(
            "send_type",
            sa.Enum("ONSIGHT", "FLASH", "REDPOINT", "ATTEMPT", name="send_type"),
            nullable=False,
        ),
        sa.Column("send_date", sa.Date(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("climb_entry")
    op.drop_table("location")
    # ### end Alembic commands ###
